apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      automountServiceAccountToken: false
      containers:
        - name: blog
          image: blog
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: blog
          resources:
            limits:
              memory: 128M
              cpu: 75m
            requests:
              memory: 128M
              cpu: 75m
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
