apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/corybuecker/blog@sha256:5bead59bc9b8eab88809d83676a56a6190bb6db0b087203bc8d0e168d30a5c9b
        ports:
        - name: http
          containerPort: 8000
        envFrom:
        - secretRef:
            name: blog
        resources:
          limits:
            memory: 128M
            cpu: 175m
          requests:
            memory: 128M
            cpu: 175m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
