apiVersion: v1
kind: Namespace
metadata:
  name: blog
  labels:
    name: blog
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
