name: branch-protection
on:
  pull_request:
    branches: main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://postgres@localhost:5432/postgres"
    steps:
      - run: docker run --name postgres -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:17.4
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
      - run: cargo test
  build:
    runs-on: ubuntu-24.04-arm
    needs:
      - lint
      - test
    permissions:
      packages: write
    steps:
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
    - uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
      with:
        push: true
        tags: ghcr.io/corybuecker/blog:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
