name: continuous-delivery

permissions:
  packages: write

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          push: true
          tags: ghcr.io/corybuecker/blog:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
